apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-kubernetes-engine-fleet-membership-display
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: Terraform Kubernetes Engine Hub Submodule
    source:
      repo: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine.git
      sourceType: git
      dir: /modules/fleet-membership
  ui:
    input:
      variables:
        cluster_name:
          name: cluster_name
          title: Cluster Name
        enable_fleet_registration:
          name: enable_fleet_registration
          title: Enable Fleet Registration
        hub_project_id:
          name: hub_project_id
          title: Hub Project Id
        location:
          name: location
          title: Location
        membership_location:
          name: membership_location
          title: Membership Location
        membership_name:
          name: membership_name
          title: Membership Name
        project_id:
          name: project_id
          title: Project Id
