apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-kubernetes-engine-binary-authorization-display
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: Binary Authorization Infrastructure
    source:
      repo: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine.git
      sourceType: git
      dir: /modules/binary-authorization
  ui:
    input:
      variables:
        attestor-name:
          name: attestor-name
          title: Attestor-Name
        crypto-algorithm:
          name: crypto-algorithm
          title: Crypto-Algorithm
        disable_dependent_services:
          name: disable_dependent_services
          title: Disable Dependent Services
        disable_services_on_destroy:
          name: disable_services_on_destroy
          title: Disable Services On Destroy
        keyring-id:
          name: keyring-id
          title: Keyring-Id
        project_id:
          name: project_id
          title: Project Id
