apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-kubernetes-engine-auth-display
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: Terraform Kubernetes Engine Auth Module
    source:
      repo: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine.git
      sourceType: git
      dir: /modules/auth
  ui:
    input:
      variables:
        cluster_name:
          name: cluster_name
          title: Cluster Name
        location:
          name: location
          title: Location
        project_id:
          name: project_id
          title: Project Id
        use_private_endpoint:
          name: use_private_endpoint
          title: Use Private Endpoint
