apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-kubernetes-engine-fleet-app-operator-permissions-display
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: Terrafrom Module for Fleet App Operator Permissions
    source:
      repo: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine.git
      sourceType: git
      dir: /modules/fleet-app-operator-permissions
  ui:
    input:
      variables:
        fleet_project_id:
          name: fleet_project_id
          title: Fleet Project Id
        groups:
          name: groups
          title: Groups
        role:
          name: role
          title: Role
        scope_id:
          name: scope_id
          title: Scope Id
        users:
          name: users
          title: Users
